# Generated by Django 4.1.4 on 2023-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0003_remove_comment_booking_remove_comment_clean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREY', 'Grey')], max_length=20),
        ),
    ]
