# Generated by Django 4.1.4 on 2023-04-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0006_booking_number_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_pax',
            field=models.IntegerField(default=0),
        ),
    ]
