# Generated by Django 4.1.4 on 2023-04-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0007_alter_booking_number_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
