# Generated by Django 4.1.4 on 2023-03-11 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_user_following_comment_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
