# Generated by Django 4.1.4 on 2023-03-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='likedposts',
        ),
    ]
