# Generated by Django 4.1.4 on 2023-01-29 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_name_listing_title_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
