# Generated by Django 4.1.4 on 2023-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_amount_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='listing',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
