# Generated by Django 4.1.4 on 2023-02-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_amount1_listing_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
