# Generated by Django 4.1.4 on 2023-02-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_bid_amount_remove_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='amount1',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price1',
            new_name='price',
        ),
    ]
