# Generated by Django 4.1.4 on 2023-02-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_user_watchlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='users_watching', to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
