# Generated by Django 4.1.4 on 2023-02-07 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
