# Generated by Django 4.1.4 on 2023-02-09 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_category_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
