# Generated by Django 4.1.4 on 2023-04-04 22:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import minilogistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accounts_owned',
        ),
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_added', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='clean',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cleans_added', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleaner',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='contractor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[(minilogistic.models.PermissionLevel['VIEW_ONLY'], 'View Only'), (minilogistic.models.PermissionLevel['EDIT'], 'Edit'), (minilogistic.models.PermissionLevel['ADMIN'], 'Admin')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to='minilogistic.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
