# Generated by Django 4.1.4 on 2023-04-10 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import minilogistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clean',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(choices=[(minilogistic.models.ColorCode['GREEN'], 'Green'), (minilogistic.models.ColorCode['RED'], 'Red'), (minilogistic.models.ColorCode['BLUE'], 'Blue')], max_length=20)),
                ('body', models.TextField(max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='minilogistic.account')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='minilogistic.booking')),
                ('clean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='minilogistic.clean')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
