# Generated by Django 4.1.4 on 2023-04-17 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import minilogistic.models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0002_alter_booking_email_alter_clean_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='clean',
        ),
        migrations.AddField(
            model_name='comment',
            name='booking_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_comments', to='minilogistic.booking'),
        ),
        migrations.AddField(
            model_name='comment',
            name='clean_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_comments', to='minilogistic.clean'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_comments', to='minilogistic.account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(choices=[(minilogistic.models.ColorCode['GREEN'], 'Green'), (minilogistic.models.ColorCode['RED'], 'Red'), (minilogistic.models.ColorCode['BLUE'], 'Blue'), (minilogistic.models.ColorCode['GREY'], 'Grey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
