# Generated by Django 4.1.4 on 2023-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0004_alter_comment_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(choices=[('GREEN', 'green'), ('RED', 'red'), ('BLUE', 'blue'), ('GREY', 'grey')], max_length=20),
        ),
    ]
