# Generated by Django 4.1.4 on 2023-03-26 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0006_alter_booking_arrival_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guestname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='booking',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
