# Generated by Django 4.1.4 on 2023-03-27 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0007_rename_guestname_booking_firstname_booking_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
