# Generated by Django 4.1.4 on 2023-03-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0008_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='selectors', to='minilogistic.user'),
            preserve_default=False,
        ),
    ]
