# Generated by Django 4.1.4 on 2023-03-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0009_selector_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='selectors', to=settings.AUTH_USER_MODEL),
        ),
    ]
