# Generated by Django 4.1.4 on 2023-03-27 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0011_alter_selector_agenda_date_alter_selector_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='agenda_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
