# Generated by Django 4.1.4 on 2023-04-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0012_alter_selector_agenda_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='booking',
        ),
    ]
