# Generated by Django 4.1.4 on 2023-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilogistic', '0013_remove_clean_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='clean',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
    ]
